/**
 * data/seed-cards.ts
 *
 * Static card catalog for initial DB seeding.
 * Games covered: Pokémon TCG (pokemon) + One Piece Card Game (onepiece)
 * Target: ~200 high-demand cards
 *
 * Structure: { game, name, setName, rarity, condition }
 * Slugs are auto-generated by scripts/seed-cards.ts.
 */

export type CardSeed = {
  game:      string;
  name:      string;
  setName:   string;
  rarity:    string;
  condition: string;
};

// ─── Pokémon TCG ──────────────────────────────────────────────────────────────
// Conditions: NM only for most; NM + LP for high-liquidity staples.
// Sets use official Japanese set codes.

const POKEMON: CardSeed[] = [
  // SV2a: ポケモンカード151
  { game: "pokemon", name: "Charizard ex",      setName: "SV2a 151",        rarity: "SAR", condition: "NM" },
  { game: "pokemon", name: "Charizard ex",      setName: "SV2a 151",        rarity: "SAR", condition: "LP" },
  { game: "pokemon", name: "Mewtwo ex",         setName: "SV2a 151",        rarity: "SAR", condition: "NM" },
  { game: "pokemon", name: "Pikachu ex",        setName: "SV2a 151",        rarity: "SAR", condition: "NM" },
  { game: "pokemon", name: "Eevee ex",          setName: "SV2a 151",        rarity: "SAR", condition: "NM" },
  { game: "pokemon", name: "Venusaur ex",       setName: "SV2a 151",        rarity: "SAR", condition: "NM" },
  { game: "pokemon", name: "Blastoise ex",      setName: "SV2a 151",        rarity: "SAR", condition: "NM" },
  { game: "pokemon", name: "Gengar ex",         setName: "SV2a 151",        rarity: "SAR", condition: "NM" },
  { game: "pokemon", name: "Alakazam ex",       setName: "SV2a 151",        rarity: "SAR", condition: "NM" },
  { game: "pokemon", name: "Gyarados ex",       setName: "SV2a 151",        rarity: "SAR", condition: "NM" },
  { game: "pokemon", name: "Dragonite ex",      setName: "SV2a 151",        rarity: "SAR", condition: "NM" },
  { game: "pokemon", name: "Mewtwo",            setName: "SV2a 151",        rarity: "HR",  condition: "NM" },
  { game: "pokemon", name: "Mew ex",            setName: "SV2a 151",        rarity: "SAR", condition: "NM" },
  { game: "pokemon", name: "Clefairy",          setName: "SV2a 151",        rarity: "AR",  condition: "NM" },
  { game: "pokemon", name: "Slowpoke",          setName: "SV2a 151",        rarity: "AR",  condition: "NM" },

  // SV3: 黒炎の支配者
  { game: "pokemon", name: "Charizard ex",      setName: "SV3 黒炎の支配者",  rarity: "SAR", condition: "NM" },
  { game: "pokemon", name: "Charizard ex",      setName: "SV3 黒炎の支配者",  rarity: "SAR", condition: "LP" },
  { game: "pokemon", name: "Charizard ex",      setName: "SV3 黒炎の支配者",  rarity: "SR",  condition: "NM" },
  { game: "pokemon", name: "Arcanine ex",       setName: "SV3 黒炎の支配者",  rarity: "SAR", condition: "NM" },
  { game: "pokemon", name: "Tyranitar ex",      setName: "SV3 黒炎の支配者",  rarity: "SAR", condition: "NM" },
  { game: "pokemon", name: "Darkrai ex",        setName: "SV3 黒炎の支配者",  rarity: "SAR", condition: "NM" },
  { game: "pokemon", name: "Skeledirge ex",     setName: "SV3 黒炎の支配者",  rarity: "SAR", condition: "NM" },
  { game: "pokemon", name: "Charmander",        setName: "SV3 黒炎の支配者",  rarity: "AR",  condition: "NM" },

  // SV4a: シャイニートレジャーex
  { game: "pokemon", name: "Pikachu ex",        setName: "SV4a シャイニートレジャーex", rarity: "SSR", condition: "NM" },
  { game: "pokemon", name: "Pikachu ex",        setName: "SV4a シャイニートレジャーex", rarity: "SSR", condition: "LP" },
  { game: "pokemon", name: "Eevee ex",          setName: "SV4a シャイニートレジャーex", rarity: "SSR", condition: "NM" },
  { game: "pokemon", name: "Charizard ex",      setName: "SV4a シャイニートレジャーex", rarity: "SSR", condition: "NM" },
  { game: "pokemon", name: "Mewtwo ex",         setName: "SV4a シャイニートレジャーex", rarity: "SSR", condition: "NM" },
  { game: "pokemon", name: "Rayquaza ex",       setName: "SV4a シャイニートレジャーex", rarity: "SSR", condition: "NM" },
  { game: "pokemon", name: "Umbreon ex",        setName: "SV4a シャイニートレジャーex", rarity: "SSR", condition: "NM" },
  { game: "pokemon", name: "Espeon ex",         setName: "SV4a シャイニートレジャーex", rarity: "SSR", condition: "NM" },
  { game: "pokemon", name: "Leafeon ex",        setName: "SV4a シャイニートレジャーex", rarity: "SSR", condition: "NM" },
  { game: "pokemon", name: "Glaceon ex",        setName: "SV4a シャイニートレジャーex", rarity: "SSR", condition: "NM" },
  { game: "pokemon", name: "Sylveon ex",        setName: "SV4a シャイニートレジャーex", rarity: "SSR", condition: "NM" },
  { game: "pokemon", name: "Flareon ex",        setName: "SV4a シャイニートレジャーex", rarity: "SSR", condition: "NM" },
  { game: "pokemon", name: "Vaporeon ex",       setName: "SV4a シャイニートレジャーex", rarity: "SSR", condition: "NM" },
  { game: "pokemon", name: "Jolteon ex",        setName: "SV4a シャイニートレジャーex", rarity: "SSR", condition: "NM" },

  // SV1: スカーレット
  { game: "pokemon", name: "Miraidon ex",       setName: "SV1 スカーレット",  rarity: "SAR", condition: "NM" },
  { game: "pokemon", name: "Koraidon ex",       setName: "SV1 スカーレット",  rarity: "SAR", condition: "NM" },
  { game: "pokemon", name: "Arcanine ex",       setName: "SV1 スカーレット",  rarity: "SAR", condition: "NM" },
  { game: "pokemon", name: "Gardevoir ex",      setName: "SV1S バイオレット", rarity: "SAR", condition: "NM" },

  // SV2: クレイバースト
  { game: "pokemon", name: "Iono",              setName: "SV2 クレイバースト", rarity: "SAR", condition: "NM" },
  { game: "pokemon", name: "Iono",              setName: "SV2 クレイバースト", rarity: "SAR", condition: "LP" },
  { game: "pokemon", name: "Garchomp ex",       setName: "SV2 クレイバースト", rarity: "SAR", condition: "NM" },
  { game: "pokemon", name: "Lucario ex",        setName: "SV2 クレイバースト", rarity: "SAR", condition: "NM" },

  // SV4: 未来の一閃 / 古代の咆哮
  { game: "pokemon", name: "Flutter Mane ex",   setName: "SV4M 未来の一閃",  rarity: "SAR", condition: "NM" },
  { game: "pokemon", name: "Iron Valiant ex",   setName: "SV4M 未来の一閃",  rarity: "SAR", condition: "NM" },
  { game: "pokemon", name: "Roaring Moon ex",   setName: "SV4K 古代の咆哮",  rarity: "SAR", condition: "NM" },
  { game: "pokemon", name: "Walking Wake ex",   setName: "SV4K 古代の咆哮",  rarity: "SAR", condition: "NM" },

  // SV5: ワイルドフォース / サイバージャッジ
  { game: "pokemon", name: "Ogerpon ex",        setName: "SV5K クリムゾンヘイズ", rarity: "SAR", condition: "NM" },
  { game: "pokemon", name: "Munkidori ex",      setName: "SV5M サイバージャッジ",  rarity: "SAR", condition: "NM" },
  { game: "pokemon", name: "Fezandipiti ex",    setName: "SV5K クリムゾンヘイズ",  rarity: "SAR", condition: "NM" },

  // SV6: マスカーニャex
  { game: "pokemon", name: "Meowscarada ex",    setName: "SV6 マスカーニャex", rarity: "SAR", condition: "NM" },
  { game: "pokemon", name: "Skeledirge ex",     setName: "SV6 マスカーニャex", rarity: "SAR", condition: "NM" },
  { game: "pokemon", name: "Quaquaval ex",      setName: "SV6 マスカーニャex", rarity: "SAR", condition: "NM" },

  // SV7: ステラミラクル
  { game: "pokemon", name: "Terapagos ex",      setName: "SV7 ステラミラクル", rarity: "SAR", condition: "NM" },
  { game: "pokemon", name: "Pecharunt ex",      setName: "SV7 ステラミラクル", rarity: "SAR", condition: "NM" },
  { game: "pokemon", name: "Raichu ex",         setName: "SV7 ステラミラクル", rarity: "SAR", condition: "NM" },

  // SV7a: 楽園ドラゴーナ
  { game: "pokemon", name: "Archaludon ex",     setName: "SV7a 楽園ドラゴーナ", rarity: "SAR", condition: "NM" },
  { game: "pokemon", name: "Hydrapple ex",      setName: "SV7a 楽園ドラゴーナ", rarity: "SAR", condition: "NM" },

  // sv8: Super Electric Breaker
  { game: "pokemon", name: "Raichu ex",         setName: "SV8 スーパーエレクトリックブレイカー", rarity: "SAR", condition: "NM" },
  { game: "pokemon", name: "Zekrom ex",         setName: "SV8 スーパーエレクトリックブレイカー", rarity: "SAR", condition: "NM" },
  { game: "pokemon", name: "Raikou ex",         setName: "SV8 スーパーエレクトリックブレイカー", rarity: "SAR", condition: "NM" },

  // Classic sets (Base Set / Neo / etc.)
  { game: "pokemon", name: "Charizard",         setName: "Base Set",         rarity: "Holo Rare",  condition: "NM" },
  { game: "pokemon", name: "Charizard",         setName: "Base Set",         rarity: "Holo Rare",  condition: "LP" },
  { game: "pokemon", name: "Charizard",         setName: "Base Set",         rarity: "Holo Rare",  condition: "MP" },
  { game: "pokemon", name: "Blastoise",         setName: "Base Set",         rarity: "Holo Rare",  condition: "NM" },
  { game: "pokemon", name: "Venusaur",          setName: "Base Set",         rarity: "Holo Rare",  condition: "NM" },
  { game: "pokemon", name: "Mewtwo",            setName: "Base Set",         rarity: "Holo Rare",  condition: "NM" },
  { game: "pokemon", name: "Chansey",           setName: "Base Set",         rarity: "Holo Rare",  condition: "NM" },
  { game: "pokemon", name: "Ninetales",         setName: "Base Set",         rarity: "Holo Rare",  condition: "NM" },
  { game: "pokemon", name: "Raichu",            setName: "Base Set",         rarity: "Holo Rare",  condition: "NM" },
  { game: "pokemon", name: "Gyarados",          setName: "Base Set",         rarity: "Holo Rare",  condition: "NM" },
  { game: "pokemon", name: "Zapdos",            setName: "Base Set",         rarity: "Holo Rare",  condition: "NM" },
  { game: "pokemon", name: "Clefairy",          setName: "Base Set",         rarity: "Holo Rare",  condition: "NM" },
  { game: "pokemon", name: "Hitmonchan",        setName: "Base Set",         rarity: "Holo Rare",  condition: "NM" },
  { game: "pokemon", name: "Machamp",           setName: "Base Set",         rarity: "Holo Rare",  condition: "NM" },
  { game: "pokemon", name: "Scyther",           setName: "Jungle",           rarity: "Holo Rare",  condition: "NM" },
  { game: "pokemon", name: "Scyther",           setName: "Jungle",           rarity: "Holo Rare",  condition: "LP" },
  { game: "pokemon", name: "Jolteon",           setName: "Jungle",           rarity: "Holo Rare",  condition: "NM" },
  { game: "pokemon", name: "Flareon",           setName: "Jungle",           rarity: "Holo Rare",  condition: "NM" },
  { game: "pokemon", name: "Vaporeon",          setName: "Jungle",           rarity: "Holo Rare",  condition: "NM" },
  { game: "pokemon", name: "Clefable",          setName: "Jungle",           rarity: "Holo Rare",  condition: "NM" },
  { game: "pokemon", name: "Gengar",            setName: "Fossil",           rarity: "Holo Rare",  condition: "NM" },
  { game: "pokemon", name: "Lapras",            setName: "Fossil",           rarity: "Holo Rare",  condition: "NM" },
  { game: "pokemon", name: "Moltres",           setName: "Fossil",           rarity: "Holo Rare",  condition: "NM" },
  { game: "pokemon", name: "Lugia",             setName: "Neo Genesis",      rarity: "Holo Rare",  condition: "NM" },
  { game: "pokemon", name: "Lugia",             setName: "Neo Genesis",      rarity: "Holo Rare",  condition: "LP" },
  { game: "pokemon", name: "Ho-Oh",             setName: "Neo Revelation",   rarity: "Holo Rare",  condition: "NM" },
  { game: "pokemon", name: "Celebi",            setName: "Neo Destiny",      rarity: "Holo Rare",  condition: "NM" },
  { game: "pokemon", name: "Espeon",            setName: "Neo Discovery",    rarity: "Holo Rare",  condition: "NM" },
  { game: "pokemon", name: "Umbreon",           setName: "Neo Discovery",    rarity: "Holo Rare",  condition: "NM" },

  // SWSH (ソード＆シールド era)
  { game: "pokemon", name: "Lugia VSTAR",       setName: "SWSH11 Lost Origin",  rarity: "SAR", condition: "NM" },
  { game: "pokemon", name: "Comfey",            setName: "SWSH11 Lost Origin",  rarity: "SAR", condition: "NM" },
  { game: "pokemon", name: "Radiant Charizard", setName: "SWSH9 Brilliant Stars", rarity: "RR", condition: "NM" },
  { game: "pokemon", name: "Arceus VSTAR",      setName: "SWSH9 Brilliant Stars", rarity: "SAR", condition: "NM" },
  { game: "pokemon", name: "Umbreon VMAX",      setName: "SWSH6 Evolving Skies",  rarity: "SAR", condition: "NM" },
  { game: "pokemon", name: "Glaceon VMAX",      setName: "SWSH6 Evolving Skies",  rarity: "SAR", condition: "NM" },
  { game: "pokemon", name: "Leafeon VMAX",      setName: "SWSH6 Evolving Skies",  rarity: "SAR", condition: "NM" },
  { game: "pokemon", name: "Rayquaza VMAX",     setName: "SWSH6 Evolving Skies",  rarity: "SAR", condition: "NM" },
  { game: "pokemon", name: "Charizard VSTAR",   setName: "SWSH9 Brilliant Stars", rarity: "SAR", condition: "NM" },

  // promo / special
  { game: "pokemon", name: "Pikachu",           setName: "Promo SWSH",       rarity: "Promo",     condition: "NM" },
  { game: "pokemon", name: "Pikachu",           setName: "Promo SV",         rarity: "Promo",     condition: "NM" },
  { game: "pokemon", name: "Eevee",             setName: "Promo SWSH",       rarity: "Promo",     condition: "NM" },
];

// ─── One Piece Card Game ──────────────────────────────────────────────────────

const ONEPIECE: CardSeed[] = [
  // OP-01: ROMANCE DAWN
  { game: "onepiece", name: "Kaido",                    setName: "OP-01 Romance Dawn",      rarity: "SEC",  condition: "NM" },
  { game: "onepiece", name: "Kaido",                    setName: "OP-01 Romance Dawn",      rarity: "SEC",  condition: "LP" },
  { game: "onepiece", name: "Shanks",                   setName: "OP-01 Romance Dawn",      rarity: "SEC",  condition: "NM" },
  { game: "onepiece", name: "Shanks",                   setName: "OP-01 Romance Dawn",      rarity: "SEC",  condition: "LP" },
  { game: "onepiece", name: "Monkey D. Luffy",          setName: "OP-01 Romance Dawn",      rarity: "SR",   condition: "NM" },
  { game: "onepiece", name: "Zoro",                     setName: "OP-01 Romance Dawn",      rarity: "SR",   condition: "NM" },
  { game: "onepiece", name: "Nami",                     setName: "OP-01 Romance Dawn",      rarity: "SR",   condition: "NM" },
  { game: "onepiece", name: "Roronoa Zoro",             setName: "OP-01 Romance Dawn",      rarity: "L",    condition: "NM" },
  { game: "onepiece", name: "Monkey D. Luffy",          setName: "OP-01 Romance Dawn",      rarity: "L",    condition: "NM" },

  // OP-02: PARAMOUNT WAR
  { game: "onepiece", name: "Portgas D. Ace",           setName: "OP-02 Paramount War",     rarity: "SEC",  condition: "NM" },
  { game: "onepiece", name: "Portgas D. Ace",           setName: "OP-02 Paramount War",     rarity: "SEC",  condition: "LP" },
  { game: "onepiece", name: "Yamato",                   setName: "OP-02 Paramount War",     rarity: "SEC",  condition: "NM" },
  { game: "onepiece", name: "Yamato",                   setName: "OP-02 Paramount War",     rarity: "SEC",  condition: "LP" },
  { game: "onepiece", name: "Uta",                      setName: "OP-02 Paramount War",     rarity: "SR",   condition: "NM" },
  { game: "onepiece", name: "Marco",                    setName: "OP-02 Paramount War",     rarity: "SR",   condition: "NM" },
  { game: "onepiece", name: "Whitebeard",               setName: "OP-02 Paramount War",     rarity: "SR",   condition: "NM" },
  { game: "onepiece", name: "Sabo",                     setName: "OP-02 Paramount War",     rarity: "SR",   condition: "NM" },

  // OP-03: PILLARS OF STRENGTH
  { game: "onepiece", name: "Charlotte Linlin",         setName: "OP-03 Pillars of Strength", rarity: "SEC", condition: "NM" },
  { game: "onepiece", name: "Eustass Kid",              setName: "OP-03 Pillars of Strength", rarity: "SR",  condition: "NM" },
  { game: "onepiece", name: "Trafalgar Law",            setName: "OP-03 Pillars of Strength", rarity: "SR",  condition: "NM" },
  { game: "onepiece", name: "Katakuri",                 setName: "OP-03 Pillars of Strength", rarity: "SR",  condition: "NM" },

  // OP-04: KINGDOMS OF INTRIGUE
  { game: "onepiece", name: "Monkey D. Luffy",          setName: "OP-04 Kingdoms of Intrigue", rarity: "SEC", condition: "NM" },
  { game: "onepiece", name: "Monkey D. Luffy",          setName: "OP-04 Kingdoms of Intrigue", rarity: "SEC", condition: "LP" },
  { game: "onepiece", name: "Nico Robin",               setName: "OP-04 Kingdoms of Intrigue", rarity: "SR",  condition: "NM" },
  { game: "onepiece", name: "Doflamingo",               setName: "OP-04 Kingdoms of Intrigue", rarity: "SR",  condition: "NM" },
  { game: "onepiece", name: "Nami",                     setName: "OP-04 Kingdoms of Intrigue", rarity: "SR",  condition: "NM" },
  { game: "onepiece", name: "Sanji",                    setName: "OP-04 Kingdoms of Intrigue", rarity: "SR",  condition: "NM" },

  // OP-05: AWAKENING OF THE NEW ERA
  { game: "onepiece", name: "Vinsmoke Sanji",           setName: "OP-05 Awakening of the New Era", rarity: "SEC", condition: "NM" },
  { game: "onepiece", name: "Vinsmoke Sanji",           setName: "OP-05 Awakening of the New Era", rarity: "SEC", condition: "LP" },
  { game: "onepiece", name: "Roronoa Zoro",             setName: "OP-05 Awakening of the New Era", rarity: "SR",  condition: "NM" },
  { game: "onepiece", name: "Perona",                   setName: "OP-05 Awakening of the New Era", rarity: "SR",  condition: "NM" },
  { game: "onepiece", name: "Hawkins",                  setName: "OP-05 Awakening of the New Era", rarity: "SR",  condition: "NM" },

  // OP-06: WINGS OF THE CAPTAIN
  { game: "onepiece", name: "Shanks",                   setName: "OP-06 Wings of the Captain",  rarity: "SEC", condition: "NM" },
  { game: "onepiece", name: "Shanks",                   setName: "OP-06 Wings of the Captain",  rarity: "SEC", condition: "LP" },
  { game: "onepiece", name: "Mihawk",                   setName: "OP-06 Wings of the Captain",  rarity: "SR",  condition: "NM" },
  { game: "onepiece", name: "Perona",                   setName: "OP-06 Wings of the Captain",  rarity: "SR",  condition: "NM" },
  { game: "onepiece", name: "Buggy",                    setName: "OP-06 Wings of the Captain",  rarity: "SR",  condition: "NM" },

  // OP-07: 500 YEARS IN THE FUTURE
  { game: "onepiece", name: "Vegapunk",                 setName: "OP-07 500 Years in the Future", rarity: "SEC", condition: "NM" },
  { game: "onepiece", name: "Bonney",                   setName: "OP-07 500 Years in the Future", rarity: "SR",  condition: "NM" },
  { game: "onepiece", name: "Kizaru",                   setName: "OP-07 500 Years in the Future", rarity: "SR",  condition: "NM" },
  { game: "onepiece", name: "Jaygarcia Saturn",         setName: "OP-07 500 Years in the Future", rarity: "SR",  condition: "NM" },

  // OP-08: TWO LEGENDS
  { game: "onepiece", name: "Gol D. Roger",             setName: "OP-08 Two Legends",       rarity: "SEC", condition: "NM" },
  { game: "onepiece", name: "Gol D. Roger",             setName: "OP-08 Two Legends",       rarity: "SEC", condition: "LP" },
  { game: "onepiece", name: "Whitebeard",               setName: "OP-08 Two Legends",       rarity: "SEC", condition: "NM" },
  { game: "onepiece", name: "Oden",                     setName: "OP-08 Two Legends",       rarity: "SR",  condition: "NM" },
  { game: "onepiece", name: "Roger",                    setName: "OP-08 Two Legends",       rarity: "SR",  condition: "NM" },
  { game: "onepiece", name: "Rayleigh",                 setName: "OP-08 Two Legends",       rarity: "SR",  condition: "NM" },

  // OP-09: EMPERORS IN THE NEW WORLD
  { game: "onepiece", name: "Monkey D. Dragon",         setName: "OP-09 Emperors in the New World", rarity: "SEC", condition: "NM" },
  { game: "onepiece", name: "Ivankov",                  setName: "OP-09 Emperors in the New World", rarity: "SR",  condition: "NM" },
  { game: "onepiece", name: "Crocodile",                setName: "OP-09 Emperors in the New World", rarity: "SR",  condition: "NM" },

  // ST Starter Decks (high-value leader foils)
  { game: "onepiece", name: "Monkey D. Luffy",          setName: "ST-01 Straw Hat Crew",    rarity: "L",   condition: "NM" },
  { game: "onepiece", name: "Trafalgar Law",            setName: "ST-03 The Seven Warlords", rarity: "L",  condition: "NM" },
  { game: "onepiece", name: "Yamato",                   setName: "ST-09 Yamato",             rarity: "L",  condition: "NM" },
  { game: "onepiece", name: "Yamato",                   setName: "ST-09 Yamato",             rarity: "L",  condition: "LP" },
  { game: "onepiece", name: "Uta",                      setName: "ST-11 Uta",                rarity: "L",  condition: "NM" },
  { game: "onepiece", name: "Roronoa Zoro",             setName: "ST-12 Zoro & Sanji",       rarity: "L",  condition: "NM" },
  { game: "onepiece", name: "Vinsmoke Sanji",           setName: "ST-12 Zoro & Sanji",       rarity: "L",  condition: "NM" },

  // Cross-era parallel rares (人気パラレル)
  { game: "onepiece", name: "Nami",                     setName: "OP-03 Pillars of Strength", rarity: "SR Parallel", condition: "NM" },
  { game: "onepiece", name: "Nico Robin",               setName: "OP-02 Paramount War",       rarity: "SR Parallel", condition: "NM" },
  { game: "onepiece", name: "Yamato",                   setName: "OP-04 Kingdoms of Intrigue", rarity: "SR Parallel", condition: "NM" },
];

// ─── Pokémon TCG (Japanese era / trainer cards) ───────────────────────────────
// Japanese set codes: sv* = SV era, s* = SWSH era, sm* = Sun & Moon era, bw* = BW era

const POKEMON_JP: CardSeed[] = [
  // SV era trainers
  { game: "pokemon", name: "ナンジャモ",        setName: "sv2D", rarity: "SAR", condition: "NM" },
  { game: "pokemon", name: "ナンジャモ",        setName: "sv2D", rarity: "SAR", condition: "LP" },
  { game: "pokemon", name: "ナンジャモ",        setName: "sv2D", rarity: "SR",  condition: "NM" },
  { game: "pokemon", name: "ミモザ",            setName: "sv1V", rarity: "SAR", condition: "NM" },
  { game: "pokemon", name: "ミモザ",            setName: "sv1V", rarity: "SR",  condition: "NM" },
  { game: "pokemon", name: "キハダ",            setName: "sv1a", rarity: "SAR", condition: "NM" },
  { game: "pokemon", name: "キハダ",            setName: "sv1a", rarity: "SR",  condition: "NM" },
  { game: "pokemon", name: "ボタン",            setName: "sv1S", rarity: "SAR", condition: "NM" },
  { game: "pokemon", name: "ボタン",            setName: "sv1S", rarity: "SR",  condition: "NM" },
  { game: "pokemon", name: "サーナイト ex",     setName: "sv1S", rarity: "SAR", condition: "NM" },
  { game: "pokemon", name: "ゲッコウガ ex",     setName: "sv2a", rarity: "SAR", condition: "NM" },
  { game: "pokemon", name: "リザードン ex",     setName: "sv2a", rarity: "SAR", condition: "NM" },
  { game: "pokemon", name: "リザードン ex",     setName: "sv2a", rarity: "SAR", condition: "LP" },
  { game: "pokemon", name: "ピカチュウ",        setName: "sv1a", rarity: "AR",  condition: "NM" },

  // SWSH era (s* series)
  { game: "pokemon", name: "カイ",              setName: "s10P", rarity: "SAR", condition: "NM" },
  { game: "pokemon", name: "カイ",              setName: "s10P", rarity: "SR",  condition: "NM" },
  { game: "pokemon", name: "セレナ",            setName: "s11a", rarity: "SR",  condition: "NM" },
  { game: "pokemon", name: "セレナ",            setName: "s11a", rarity: "HR",  condition: "NM" },
  { game: "pokemon", name: "マリィ",            setName: "s4a",  rarity: "SR",  condition: "NM" },
  { game: "pokemon", name: "マリィのプライド",  setName: "sI",   rarity: "SR",  condition: "NM" },
  { game: "pokemon", name: "ユウリ",            setName: "s8b",  rarity: "SR",  condition: "NM" },
  { game: "pokemon", name: "リザードン VSTAR",  setName: "s9",   rarity: "HR",  condition: "NM" },
  { game: "pokemon", name: "リザードン VMAX",   setName: "s4a",  rarity: "SSR", condition: "NM" },
  { game: "pokemon", name: "ブラッキー VMAX",   setName: "s6a",  rarity: "HR",  condition: "NM" },
  { game: "pokemon", name: "ブラッキー VMAX",   setName: "s6a",  rarity: "HR",  condition: "LP" },
  { game: "pokemon", name: "ニンフィア VMAX",   setName: "s6a",  rarity: "HR",  condition: "NM" },
  { game: "pokemon", name: "グレイシア VMAX",   setName: "s6a",  rarity: "HR",  condition: "NM" },
  { game: "pokemon", name: "リーフィア VMAX",   setName: "s6a",  rarity: "HR",  condition: "NM" },
  { game: "pokemon", name: "ミュウ VMAX",       setName: "s8",   rarity: "HR",  condition: "NM" },
  { game: "pokemon", name: "ピカチュウ",        setName: "s8b",  rarity: "CSR", condition: "NM" },
  { game: "pokemon", name: "ボスの指令",        setName: "s2",   rarity: "SR",  condition: "NM" },

  // Sun & Moon era (sm* series)
  { game: "pokemon", name: "リーリエ",          setName: "sm4+", rarity: "SR",  condition: "NM" },
  { game: "pokemon", name: "アセロラ",          setName: "sm2+", rarity: "SR",  condition: "NM" },
  { game: "pokemon", name: "ルチア",            setName: "sm7",  rarity: "SR",  condition: "NM" },
  { game: "pokemon", name: "シロナ",            setName: "sm5M", rarity: "SR",  condition: "NM" },
  { game: "pokemon", name: "シロナ&カトレア",   setName: "sm12", rarity: "SR",  condition: "NM" },
  { game: "pokemon", name: "かんこうきゃく",   setName: "sm12a", rarity: "SR", condition: "NM" },
  { game: "pokemon", name: "メイ",              setName: "sm11b", rarity: "SR", condition: "NM" },
  { game: "pokemon", name: "ヒガナ",            setName: "sm6a", rarity: "SR",  condition: "NM" },
  { game: "pokemon", name: "リザードン GX",     setName: "sm3H", rarity: "HR",  condition: "NM" },
  { game: "pokemon", name: "ブラッキー GX",     setName: "sm1M", rarity: "HR",  condition: "NM" },
  { game: "pokemon", name: "ミュウツー GX",     setName: "sm3+", rarity: "HR",  condition: "NM" },

  // BW era (bw* series)
  { game: "pokemon", name: "フウロ",            setName: "bw7",  rarity: "SR",  condition: "NM" },
  { game: "pokemon", name: "ベル",              setName: "bw6",  rarity: "SR",  condition: "NM" },

  // Promo
  { game: "pokemon", name: "ピカチュウ",        setName: "S-P",  rarity: "プロモ 001", condition: "NM" },
  { game: "pokemon", name: "ピカチュウ",        setName: "S-P",  rarity: "プロモ 323", condition: "NM" },

  // 旧裏 (Classic Japanese Base Set)
  { game: "pokemon", name: "リザードン",        setName: "旧裏 第1弾", rarity: "キラ", condition: "NM" },
  { game: "pokemon", name: "リザードン",        setName: "旧裏 第1弾", rarity: "キラ", condition: "LP" },
];

// ─── One Piece: Community Parallel (コミパラ) ─────────────────────────────────
// コミパラ = event-exclusive parallel cards sold at community events.
// Prices differ significantly from regular/SEC versions.

const ONEPIECE_COMIPARA: CardSeed[] = [
  { game: "onepiece", name: "モンキー・D・ルフィ",   setName: "OP-05", rarity: "コミパラ", condition: "NM" },
  { game: "onepiece", name: "ポートガス・D・エース", setName: "OP-02", rarity: "コミパラ", condition: "NM" },
  { game: "onepiece", name: "シャンクス",            setName: "OP-01", rarity: "コミパラ", condition: "NM" },
  { game: "onepiece", name: "サボ",                  setName: "OP-04", rarity: "コミパラ", condition: "NM" },
  { game: "onepiece", name: "トラファルガー・ロー",  setName: "OP-05", rarity: "コミパラ", condition: "NM" },
  { game: "onepiece", name: "ナミ",                  setName: "OP-01", rarity: "パラレル", condition: "NM" },
  { game: "onepiece", name: "ナミ",                  setName: "OP-02", rarity: "SR パラレル", condition: "NM" },
  { game: "onepiece", name: "ロビン",                setName: "OP-03", rarity: "パラレル", condition: "NM" },
  { game: "onepiece", name: "ハンコック",            setName: "OP-01", rarity: "パラレル", condition: "NM" },
  { game: "onepiece", name: "ルフィ",                setName: "OP-01", rarity: "リーダーパラレル", condition: "NM" },
  { game: "onepiece", name: "ゾロ",                  setName: "OP-01", rarity: "リーダーパラレル", condition: "NM" },
  { game: "onepiece", name: "キッド",                setName: "OP-02", rarity: "リーダーパラレル", condition: "NM" },
  { game: "onepiece", name: "ロー",                  setName: "OP-02", rarity: "リーダーパラレル", condition: "NM" },
  { game: "onepiece", name: "カイドウ",              setName: "OP-01", rarity: "SR パラレル", condition: "NM" },
  { game: "onepiece", name: "ビッグマム",            setName: "OP-03", rarity: "SR パラレル", condition: "NM" },
  { game: "onepiece", name: "ヤマト",                setName: "OP-01", rarity: "SEC パラレル", condition: "NM" },
  { game: "onepiece", name: "ウタ",                  setName: "OP-02", rarity: "SEC パラレル", condition: "NM" },
];

// ─── Yu-Gi-Oh ─────────────────────────────────────────────────────────────────

const YUGIOH: CardSeed[] = [
  { game: "yugioh", name: "青眼の白龍",          setName: "初期 第1弾",    rarity: "ウルトラレア", condition: "NM" },
  { game: "yugioh", name: "青眼の白龍",          setName: "初期 第1弾",    rarity: "ウルトラレア", condition: "LP" },
  { game: "yugioh", name: "青眼の白龍",          setName: "レリーフ",       rarity: "レリーフレア", condition: "NM" },
  { game: "yugioh", name: "ブラック・マジシャン", setName: "初期 第1弾",    rarity: "ウルトラレア", condition: "NM" },
  { game: "yugioh", name: "ブラック・マジシャン・ガール", setName: "20th", rarity: "20thシークレット", condition: "NM" },
  { game: "yugioh", name: "真紅眼の黒竜",        setName: "レリーフ",       rarity: "レリーフレア", condition: "NM" },
  { game: "yugioh", name: "万物創世龍",          setName: "QCCP",           rarity: "10000シークレット", condition: "NM" },
  { game: "yugioh", name: "ブラック・ローズ・ドラゴン", setName: "レリーフ", rarity: "レリーフレア", condition: "NM" },
  { game: "yugioh", name: "閃刀姫－レイ",        setName: "20th",           rarity: "20thシークレット", condition: "NM" },
  { game: "yugioh", name: "灰流うらら",          setName: "プリズマ",       rarity: "プリズマティックシークレット", condition: "NM" },
  { game: "yugioh", name: "増殖するG",           setName: "20th",           rarity: "20thシークレット", condition: "NM" },
];

// ─── Magic: The Gathering ─────────────────────────────────────────────────────

const MTG: CardSeed[] = [
  { game: "mtg", name: "Black Lotus",    setName: "Alpha",   rarity: "Rare",     condition: "NM" },
  { game: "mtg", name: "Black Lotus",    setName: "Beta",    rarity: "Rare",     condition: "NM" },
  { game: "mtg", name: "Black Lotus",    setName: "Unlimited", rarity: "Rare",   condition: "NM" },
  { game: "mtg", name: "Mox Jet",        setName: "Alpha",   rarity: "Rare",     condition: "NM" },
  { game: "mtg", name: "Mox Jet",        setName: "Beta",    rarity: "Rare",     condition: "NM" },
  { game: "mtg", name: "Underground Sea", setName: "Revised", rarity: "Rare",    condition: "NM" },
  { game: "mtg", name: "Underground Sea", setName: "Revised", rarity: "Rare",    condition: "LP" },
  { game: "mtg", name: "Volcanic Island", setName: "Revised", rarity: "Rare",    condition: "NM" },
  { game: "mtg", name: "Volcanic Island", setName: "Revised", rarity: "Rare",    condition: "LP" },
  { game: "mtg", name: "Time Walk",      setName: "Alpha",   rarity: "Rare",     condition: "NM" },
  { game: "mtg", name: "Time Walk",      setName: "Beta",    rarity: "Rare",     condition: "NM" },
];

export const ALL_CARDS: CardSeed[] = [
  ...POKEMON,
  ...POKEMON_JP,
  ...ONEPIECE,
  ...ONEPIECE_COMIPARA,
  ...YUGIOH,
  ...MTG,
];

export function getCardsByGame(game: string): CardSeed[] {
  return ALL_CARDS.filter((c) => c.game === game);
}
